### ISSUE TITLE
Intermittent test failure on DiscoveryServiceTest

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#116]
```
testBrokerDiscoveryRoundRobin(com.yahoo.pulsar.discovery.service.DiscoveryServiceTest)  Time elapsed: 0.493 sec  <<< FAILURE!
com.yahoo.pulsar.discovery.service.PulsarServerException: No active broker is available
	at com.yahoo.pulsar.discovery.service.DiscoveryServiceTest.testBrokerDiscoveryRoundRobin(DiscoveryServiceTest.java:82)
testClientServerConnectionTls(com.yahoo.pulsar.discovery.service.DiscoveryServiceTest)  Time elapsed: 1.168 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at com.yahoo.pulsar.discovery.service.DiscoveryServiceTest.testClientServerConnectionTls(DiscoveryServiceTest.java:116)
```

**Comment by merlimat** [comment]
@rdhabalia `testBrokerDiscoveryRoundRobin` is still failing from time to time

**Comment by rdhabalia** [comment]
yes, I will look into it.
