### ISSUE TITLE
switch active consumer but failed

### ISSUE THREAD

**Issue by patterncat** [yahoo/pulsar#20]
#### Expected behavior

i shutdown a topic's consumer and restart another consumer of the same topic but with error

#### Actual behavior

2016-09-18 10:23:33,429 - ERROR - [bookkeeper-ml-workers-33-1:SafeRunnable@33] - Unexpected throwable caught

java.lang.UnsupportedOperationException

	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.set(CopyOnWriteArrayList.java:1185)

	at java.util.Collections.sort(Collections.java:234)

	at com.yahoo.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.pickAndScheduleActiveConsumer(PersistentDispatcherSingleActiveConsumer.java:75)

	at com.yahoo.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.addConsumer(PersistentDispatcherSingleActiveConsumer.java:106)

	at com.yahoo.pulsar.broker.service.persistent.PersistentSubscription.addConsumer(PersistentSubscription.java:118)

	at com.yahoo.pulsar.broker.service.persistent.PersistentTopic$2.openCursorComplete(PersistentTopic.java:334)

	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$6.operationComplete(ManagedLedgerImpl.java:566)

	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$2.operationComplete(ManagedCursorImpl.java:275)

	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$24.operationComplete(ManagedCursorImpl.java:1844)

	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$24.operationComplete(ManagedCursorImpl.java:1834)

	at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$66(MetaStoreImplZookeeper.java:254)

	at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper$$Lambda$60/2049457780.run(Unknown Source)

	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:27)

	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)

	at java.lang.Thread.run(Thread.java:745)

#### Steps to reproduce

start a consumer and subscribe topic a 
shutdown consumer
start another consumer and subscribe topic a

#### System configuration
**Pulsar version**: 1.14

**Comment by merlimat** [comment]
This part of code gets executed every time a consumer connects and we never saw this error.

`Collections.sort()` should not call `set()` on the iterator itself, and in the latest JDK it's not doing it. I also don't see that line at `Collections.java:234`. Can you specify which JDK version you're using?

In any case, in `PersistentDispatcherSingleActiveConsumer.java:75` using `list.sort()` instead of `Collections.sort(list)` might fix the issue.

**Comment by merlimat** [comment]
Just verified, earlier JDK8 versions were using the `iterator.set()` instead of relying on the `list.sort()` interface.

Workaround for now is to upgrade your JDK.

**Comment by patterncat** [comment]
ok, thanks very much.

**Comment by patterncat** [comment]
my jdk info is (running on ubuntu:14.04):
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

**Comment by merlimat** [comment]
It was fixed in jdk-1.8.0_20 : http://bugs.java.com/view_bug.do?bug_id=8032636
