### ISSUE TITLE
Fail to reset-cursor on partitioned topic

### ISSUE THREAD

**Issue by sschepens** [yahoo/pulsar#309]
After issues with ZK #308 we are attempting to reset some consumers and we're getting the following exceptions.
How and why can a `ManagedCursorImpl` have a `ReadOnlyLedgerHandle`?

```
Caused by: com.yahoo.pulsar.broker.service.BrokerServiceException$SubscriptionInvalidCursorPosition: unable to persist position for cursor reset 730778:44020
	at com.yahoo.pulsar.broker.service.persistent.PersistentSubscription$5$1.resetFailed(PersistentSubscription.java:371)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$7.operationFailed(ManagedCursorImpl.java:746)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$persistPosition$12(ManagedCursorImpl.java:1911)
	at org.apache.bookkeeper.client.ReadOnlyLedgerHandle.asyncAddEntry(ReadOnlyLedgerHandle.java:105)
	at org.apache.bookkeeper.client.ReadOnlyLedgerHandle.asyncAddEntry(ReadOnlyLedgerHandle.java:98)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.persistPosition(ManagedCursorImpl.java:1889)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.internalResetCursor(ManagedCursorImpl.java:768)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$asyncResetCursor$4(ManagedCursorImpl.java:780)
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:27)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
```

**Comment by sschepens** [comment]
The state of that consumer in that partition is:
```
    "7621bdff98154778b082d362e5490520-sem-gps_mlm" : {
      "markDeletePosition" : "566917:35285",
      "readPosition" : "566917:35286",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : -2966888,
      "cursorLedger" : 701872,
      "cursorLedgerLastEntry" : 1,
      "individuallyDeletedMessages" : "[(566917:35286‥620386:25392], (620386:25393‥628296:34483], (628296:34484‥654199:1618], (654199:1619‥659017:48446], (659017:48447‥679414:36857], (679414:36858‥680901:49317], (680901:49318‥682083:9805], (682083:9806‥682083:11646], (682083:11647‥683799:15090], (683799:15091‥684740:22556], (684740:22557‥685652:24167], (685652:24168‥685652:26223], (685652:26224‥685652:32989], (685652:32990‥686322:18693], (686322:18694‥686322:21945], (686322:21946‥686322:22203], (686322:22204‥686322:26791], (686322:26792‥686322:27396], (686322:27397‥686857:41421], (686857:41422‥687180:39997], (687180:39998‥687981:17711], (687981:17712‥688971:40255], (688971:40256‥690115:21199], (690115:21200‥691739:24453], (691739:24454‥691739:24886], (691739:24887‥691739:34095], (691739:34096‥691739:37104], (691739:37105‥691739:38179], (691739:38180‥693222:8367], (693222:8368‥694265:36928], (694265:36929‥694265:39195], (694265:39196‥697447:3648], (697447:3649‥697890:45761], (697890:45762‥700410:3789], (700410:3790‥700410:26734], (700410:26735‥701287:47336], (701287:47343‥701287:47582], (701287:47593‥701287:47736], (701287:47743‥701287:47823], (701287:47830‥701287:47872], (701287:47880‥701287:47941], (701287:47943‥701287:47976], (701287:47993‥701287:48014], (701287:48043‥701287:48058], (701287:48093‥701287:48111], (701287:48141‥701287:48158], (701287:48188‥701287:48197], (701287:48238‥701287:48247], (701287:48289‥701287:48306], (701287:48377‥701287:48382], (701287:48426‥701287:48428], (701287:48477‥701287:48492], (701287:48526‥701287:48532], (701287:48576‥701287:48579], (701287:48626‥701287:48628], (701287:48967‥701287:48973]]",
      "lastLedgerSwitchTimestamp" : "2017-03-22 20:38:15.660",
      "state" : "NoLedger"
    },
```
What's weird is that it's in a NoLedger state and it is not creating a new one

**Comment by merlimat** [comment]
The ledger is in read-only because it was assigned after the recovery from the ledger itself. 

It is being assigned at [ManagedCursorImpl.java#L243](https://github.com/yahoo/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L243). This is wrong because it doesn't make sense to save that ledgerId.

The `NoLedger` state is valid and expected after recovering a cursor and not issuing any delete/markDelete requests. The reason is that we want to "recover" a topic in the least possible number of steps, especially in terms of ZK writes (and creating a ledger involves few ZK writes), so we defer it for later.

In this case the reset cursor should trigger the creation of a new ledger, the same as when the 1st markDelete request is issued.
