### ISSUE TITLE
Intermittent test failure on BacklogQuotaManagerTest.testAheadProducerOnHoldTimeout

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#33]
Seen intermittently in travis builds. Unfortunately the exception stack trace is not being printed fully.

```
com.yahoo.pulsar.client.admin.internal.BrokerStatsImpl$$EnhancerByMockitoWithCGLIB$$7141231b@443bf7aa
Tests run: 361, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 825.674 sec <<< FAILURE! - in TestSuite
testAheadProducerOnHoldTimeout(com.yahoo.pulsar.broker.service.BacklogQuotaManagerTest)  Time elapsed: 8.691 sec  <<< FAILURE!
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at com.yahoo.pulsar.broker.service.BacklogQuotaManagerTest.testAheadProducerOnHoldTimeout(BacklogQuotaManagerTest.java:504)
```

**Comment by merlimat** [comment]
Got a stack trace of one failed run out of 100 passed : 

```
Got exception : io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at com.yahoo.pulsar.client.impl.ProducerImpl.lambda$closeAsync$0(ProducerImpl.java:376)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.yahoo.pulsar.client.impl.ProducerImpl.closeAsync(ProducerImpl.java:376)
	at com.yahoo.pulsar.client.impl.PulsarClientImpl.lambda$closeAsync$4(PulsarClientImpl.java:314)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.yahoo.pulsar.client.impl.PulsarClientImpl.closeAsync(PulsarClientImpl.java:314)
	at com.yahoo.pulsar.client.impl.PulsarClientImpl.close(PulsarClientImpl.java:287)
	at com.yahoo.pulsar.broker.service.BacklogQuotaManagerTest.testAheadProducerOnHoldTimeout(BacklogQuotaManagerTest.java:506)
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Tests run: 100, Failures: 1, Errors: 0, Skipped: 32, Time elapsed: 689.745 sec <<< FAILURE! - in com.yahoo.pulsar.broker.service.BacklogQuotaManagerTest
```
