### ISSUE TITLE
Travis build is getting stuck for 10min

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#434]
Since few days, the build on master is getting stuck on Travis. 

eg: https://travis-ci.org/yahoo/pulsar/builds/235347858

**Comment by rdhabalia** [comment]
Recently found that multiple times testcases get stuck due to some deadlock condition. I was able to reproduce for one of the test case:

```
"pulsar-web-2757-13":
        at org.apache.zookeeper.MockZooKeeper.lambda$3(MockZooKeeper.java:245)
        - waiting to lock <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$14/1053967012.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.getData(MockZooKeeper.java:243)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.lambda$5(ZooKeeperCache.java:292)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache$$Lambda$10/249177573.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.lambda$get$2(LocalAsyncLoadingCache.java:126)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache$$Lambda$11/905080434.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$12/1344519051.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        - locked <0x000000079915fc28> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:125)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:117)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.getDataAsync(ZooKeeperCache.java:286)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache.getAsync(ZooKeeperDataCache.java:62)
        at com.yahoo.pulsar.broker.namespace.OwnershipCache.getOwnerAsync(OwnershipCache.java:189)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.findBrokerServiceUrl(NamespaceService.java:283)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.lambda$0(NamespaceService.java:132)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$Lambda$109/1534543810.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.getBrokerServiceUrlAsync(NamespaceService.java:132)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$EnhancerByMockitoWithCGLIB$$6d2de1de.CGLIB$getBrokerServiceUrlAsync$0(<generated>)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$EnhancerByMockitoWithCGLIB$$6d2de1de$$FastClassByMockitoWithCGLIB$$82215ef5.invoke(<generated>)
        at org.mockito.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:216)
        at org.powermock.api.mockito.repackaged.DelegatingMockitoMethodProxy.invokeSuper(DelegatingMockitoMethodProxy.java:20)
        at org.mockito.internal.invocation.realmethod.DefaultRealMethod.invoke(DefaultRealMethod.java:21)
        at org.mockito.internal.invocation.realmethod.CleanTraceRealMethod.invoke(CleanTraceRealMethod.java:30)
        at org.mockito.internal.invocation.InvocationImpl.callRealMethod(InvocationImpl.java:112)
        at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:41)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:93)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
        at org.powermock.api.mockito.repackaged.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:60)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$EnhancerByMockitoWithCGLIB$$6d2de1de.getBrokerServiceUrlAsync(<generated>)
        at com.yahoo.pulsar.broker.lookup.DestinationLookup.lookupDestinationAsync(DestinationLookup.java:100)
        at com.yahoo.pulsar.broker.lookup.DestinationLookup.lookupNonPersistentDestinationAsync(DestinationLookup.java:66)
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
        at com.yahoo.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
"zk-cache-callback-2716-1":
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1868)
        - waiting to lock <0x000000079915fc28> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:125)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:117)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.getDataAsync(ZooKeeperCache.java:286)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache.getAsync(ZooKeeperDataCache.java:62)
        at com.yahoo.pulsar.broker.namespace.OwnershipCache.getOwnerAsync(OwnershipCache.java:189)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.findBrokerServiceUrl(NamespaceService.java:283)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.lambda$0(NamespaceService.java:132)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$Lambda$109/1534543810.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.common.naming.NamespaceBundleFactory.lambda$2(NamespaceBundleFactory.java:80)
        at com.yahoo.pulsar.common.naming.NamespaceBundleFactory$$Lambda$71/1037942373.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$2.lambda$2(LocalZooKeeperCacheService.java:91)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$2$$Lambda$68/1720865719.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService.lambda$4(LocalZooKeeperCacheService.java:204)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$$Lambda$107/430411351.processResult(Unknown Source)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:79)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:187)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$1/1500608548.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.create(MockZooKeeper.java:173)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.bookkeeper.util.ZkUtils.asyncCreateFullPathOptimistic(ZkUtils.java:74)
        at org.apache.bookkeeper.util.ZkUtils$1$1.processResult(ZkUtils.java:95)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:79)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:187)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$1/1500608548.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.create(MockZooKeeper.java:173)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.bookkeeper.util.ZkUtils.asyncCreateFullPathOptimistic(ZkUtils.java:74)
        at org.apache.bookkeeper.util.ZkUtils$1$1.processResult(ZkUtils.java:95)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:79)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:187)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$1/1500608548.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.create(MockZooKeeper.java:173)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.bookkeeper.util.ZkUtils.asyncCreateFullPathOptimistic(ZkUtils.java:74)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:87)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:184)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$1/1500608548.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.create(MockZooKeeper.java:173)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.bookkeeper.util.ZkUtils.asyncCreateFullPathOptimistic(ZkUtils.java:74)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:87)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:184)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
		at org.apache.zookeeper.MockZooKeeper$$Lambda$1/1500608548.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.create(MockZooKeeper.java:173)
        - locked <0x000000079ff4f388> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.bookkeeper.util.ZkUtils.asyncCreateFullPathOptimistic(ZkUtils.java:74)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService.lambda$2(LocalZooKeeperCacheService.java:199)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$$Lambda$66/854989361.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService.lambda$0(LocalZooKeeperCacheService.java:167)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$$Lambda$64/1824570614.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache.lambda$0(ZooKeeperDataCache.java:63)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache$$Lambda$60/1428726828.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.lambda$6(ZooKeeperCache.java:317)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache$$Lambda$18/512549200.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.lambda$10(ZooKeeperCache.java:298)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache$$Lambda$32/1337829755.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```


It seems like it is mainly happening due to deadlock between `ZkUtils->MockZooKeeper` and `ZooKeeperCache(com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973))`.

eg:
(1) MockZooKeeper acquires mutex after creating a znode and it's callback waits on ZkCache-lock that acquires in below step2:
 On lookup to find service-url->
```
       - waiting to lock <0x000000079923e9f8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:125)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:117)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.getDataAsync(ZooKeeperCache.java:286)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache.getAsync(ZooKeeperDataCache.java:62)
        at com.yahoo.pulsar.broker.namespace.OwnershipCache.getOwnerAsync(OwnershipCache.java:189)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.findBrokerServiceUrl(NamespaceService.java:283)
        at com.yahoo.pulsar.broker.namespace.NamespaceService.lambda$0(NamespaceService.java:132)
        at com.yahoo.pulsar.broker.namespace.NamespaceService$$Lambda$109/19709373.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.common.naming.NamespaceBundleFactory.lambda$2(NamespaceBundleFactory.java:80)
        at com.yahoo.pulsar.common.naming.NamespaceBundleFactory$$Lambda$71/710220387.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$2.lambda$2(LocalZooKeeperCacheService.java:91)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$2$$Lambda$68/1424788681.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService.lambda$4(LocalZooKeeperCacheService.java:204)
        at com.yahoo.pulsar.broker.cache.LocalZooKeeperCacheService$$Lambda$107/1056863997.processResult(Unknown Source)
        at org.apache.bookkeeper.util.ZkUtils$1.processResult(ZkUtils.java:79)
        at org.apache.zookeeper.MockZooKeeper.lambda$1(MockZooKeeper.java:189)
        - locked <0x000000079d08af40> (a org.apache.zookeeper.MockZooKeeper)
```

(2) And some other thread: first takes lock on ZKCache(com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)) and then go to MockZooKeeper to get data which waits for acquired mutex on step 1.

```
"pulsar-web-3779-12":
        at org.apache.zookeeper.MockZooKeeper.lambda$3(MockZooKeeper.java:247)
        - waiting to lock <0x000000079d08af40> (a org.apache.zookeeper.MockZooKeeper)
        at org.apache.zookeeper.MockZooKeeper$$Lambda$14/1670993182.run(Unknown Source)
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
        at org.apache.zookeeper.MockZooKeeper.getData(MockZooKeeper.java:245)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.lambda$5(ZooKeeperCache.java:292)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache$$Lambda$10/2048537720.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.lambda$get$2(LocalAsyncLoadingCache.java:126)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache$$Lambda$11/1265012928.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1973)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$12/801569151.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        - locked <0x000000079923e9f8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1971)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1954)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:125)
        at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:117)
        at com.yahoo.pulsar.zookeeper.ZooKeeperCache.getDataAsync(ZooKeeperCache.java:286)
        at com.yahoo.pulsar.zookeeper.ZooKeeperDataCache.getAsync(ZooKeeperDataCache.java:62)

```

**Comment by merlimat** [comment]
The only recent change on `MockZooKeeper` was 01b510464a0ea153dfe20ccef0cc0e1173bbb055. Can it be somewhat related?

**Comment by rdhabalia** [comment]
I don't think so, because it is kind of dead-lock between `MockZooKeeper` and `Caffeine.ConcurrentHashMap (from ZKCache)` where 1 thread first takes mutex on MockZk and same thread process callback which eventually hits `Caffeine.ConcurrentHashMap` and other end 2nd thread first hits `Caffeine.ConcurrentHashMap`  and it tries to get data from `MockZk`. So, we need to break this deadlock. I will create a PR for MockZk.
