### ISSUE TITLE
no reply from websocket proxy

### ISSUE THREAD

**Issue by hrsakai** [yahoo/pulsar#458]
#### Expected behavior
websocket proxy returns correct response.

#### Actual behavior

we execute the following script about 2 to 100 times, websocket proxy often has come to return no more response.

#### Steps to reproduce
```
# execute python script
$for i in `seq 1 1000`;do python3.5 ./websocket_produce.py;done;
create 0
create 1
create 2
create 3
create 4
create 5
create 6
create 7
create 8
create 9
=======================================================
create 0
create 2
create 3
create 4
create 5
create 6
create 7
create 9
create 8
create 1
=======================================================
・
・
#no reply
```

websocket_produce.py
```
# -*- coding:utf-8 -*-
import websocket, base64, json, sys
from multiprocessing import Pool
from multiprocessing import Process

cert = '<value>'
def create_producer(i):
    print('create '+str(i))
    return websocket.create_connection(
       'ws://<hostname>:<port>/ws/producer/persistent/prop/global/n1/topic2',  header=['cert-header-name: ' + cert])

def send_message(producer):
    s=base64.b64encode(b'abcdefg').decode('utf-8')
    message = "{\"payload\":\"" + s + "\"}"
    producer.send(message)
#    print(json.loads(producer.recv()))

p = Pool(10)
# 1. create 10 producers
producers = p.map(create_producer, range(10))
# 2. send 10messages per producer 
for i in range(10):
    p.map(send_message, producers)

print("=======================================================")
```  
    
   
   
we confirmed following when this problem occurred.
1 .  when executing ``getSession().getRemote().sendString(msg)``, suddenly ``onWebSocketError()`` is called. 
[ProducerHandler.java#L130](https://github.com/yahoo/pulsar/blob/afaa63fdaa53bc04554329b43ddbf95c5b158ae8/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java#L130)
[ProducerHandler.java#L114](https://github.com/yahoo/pulsar/blob/afaa63fdaa53bc04554329b43ddbf95c5b158ae8/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java#L114)
```
14:21:16.868 [pulsar-client-io-56-1] INFO  c.y.p.w.AbstractWebSocketHandler     - [/172.21.219.252:54150] WebSocket error on topic persistent://prop/global/n1/topic2 : null
```
2 .  and another thread calls ``onWebSocketClose()``.
```
14:21:16.876 [pulsar-web-46-15] INFO  c.y.p.w.AbstractWebSocketHandler     - [/172.21.219.252:54150] Closed WebSocket session on topic persistent://prop/global/n1/topic2. status: 1006 - reason: WebSocket Read EOF
```

3 .  after next time, request is stoped in ``ctx.writeAndFlush(request)`` and no reply from websocket proxy
[ClientCnx.java#L349](https://github.com/yahoo/pulsar/blob/029b8b09ffccad8d6021958a258d58c3ab649378/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ClientCnx.java#L349)
  
4 .  no reply from admin API, too.
  

#### System configuration
**Pulsar version**: 1.17.2  and updated the latest version(current master) but This problem still occurred.
websocket proxy and broker run in same server.
   

Do you know what could be happening?

**Comment by yush1ga** [comment]
Let me share the additional investigation for the problem in same environment after @hrsakai .

I checked thread dump about "pulsar-web-\*" when the problem occurred because our additional log stopped [here](https://github.com/yahoo/pulsar/blob/v1.17.2/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/BinaryProtoLookupService.java#L134) on "pulsar-web-*" thread.
All of "pulsar-web-\*" threads are waiting `CompletableFuture.get()`  to close or create producer.

```
"pulsar-web-46-17" #111 prio=5 os_prio=0 tid=0x00007f2f0418e000 nid=0x493d waiting on condition [0x00007f2eda555000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000f47e4650> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.yahoo.pulsar.client.impl.ProducerBase.close(ProducerBase.java:73)
        at com.yahoo.pulsar.websocket.ProducerHandler.close(ProducerHandler.java:64)
        at com.yahoo.pulsar.websocket.AbstractWebSocketHandler.onWebSocketClose(AbstractWebSocketHandler.java:106)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onClose(JettyListenerEventDriver.java:98)
        at org.eclipse.jetty.websocket.common.WebSocketSession.notifyClose(WebSocketSession.java:414)
        at org.eclipse.jetty.websocket.common.WebSocketSession.onConnectionStateChange(WebSocketSession.java:445)
        at org.eclipse.jetty.websocket.common.io.IOState.notifyStateListeners(IOState.java:184)
        at org.eclipse.jetty.websocket.common.io.IOState.onReadFailure(IOState.java:498)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:666)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)

"pulsar-web-46-16" #109 prio=5 os_prio=0 tid=0x00007f2f042c4000 nid=0x490f waiting on condition [0x00007f2eda757000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000f4735e30> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.yahoo.pulsar.client.impl.PulsarClientImpl.createProducer(PulsarClientImpl.java:130)
        at com.yahoo.pulsar.websocket.ProducerHandler.onWebSocketConnect(ProducerHandler.java:74)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onConnect(JettyListenerEventDriver.java:106)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:229)
        at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:503)
        at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:432)
        at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:198)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:566)
        at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:200)
        at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:378)
        at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:622)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:453)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
```

To avoid it, I added 
```
protected final static ExecutorService executors = Executors.newScheduledThreadPool(1,
            new DefaultThreadFactory("pulsar-websocket"));
```
to AbstractWebSocketHandler and made all of `onWebSocket*` methods in `executors.execute(()->{})` block.
However, I think it is not best practice at all.

If you have some great ideas, please tell us.

**Comment by nelson-maltez** [comment]
Hello, 

This employee can no longer access email on this account.  Your email will not be forwarded.

If you have a sales inquiry, please contact sales@yahoo-inc.com

If you require assistance with a legal matter, please contact legal-notices@yahoo-inc.com

Thank you!
